#!/usr/bin/env bash
# This script displays numbers 1 to 20 with special bad luck messages

i=l
while [ "$i" -le 20 ]
do
case "$i" in 4) echo "4"
echo "bad luck from China"
;;
9)
echo "9"
echo "bad kuck from Japan"
;;
17)
echo "17"
echo "bad luck from Italy"
;;
*)
echo "$i"
;;
esac
i=$((i + l))
done
